[package]
name = "rusthelloworld"
version = "0.1.0"
authors = ["Bradley Bellairs <bwbellairs@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "rusthelloworld"
path = "main.rs"
